/**
 * English Profile — Question Bank
 * -----------------------------------------------------------------------
 * 5 parallel test forms (A–E), each with 30 original questions:
 *   6 Grammar · 6 Vocabulary · 6 Comprehension · 6 Functional Communication · 6 Naturalness
 *
 * All questions are original and were NOT copied from Cambridge, IELTS,
 * TOEFL, British Council, or any other test provider. CEFR (A1–C1)
 * descriptors were used only as a conceptual guide for calibrating
 * difficulty and content domains — not as a source of test content.
 *
 * Fields per question:
 *   id            unique identifier, e.g. "A-GR-3"
 *   construct     "grammar" | "vocabulary" | "comprehension" | "functional" | "naturalness"
 *   targetLevel   "A1" | "A2" | "B1" | "B2" | "C1"
 *   difficulty    "easy" | "medium" | "hard"  (rough proxy, aligned with targetLevel)
 *   question      the prompt (a short passage/notice is included inline for comprehension items)
 *   options       array of 4 strings
 *   correctAnswer index (0-3) of the correct option
 *   explanation   one-line rationale, used on the (optional) review view
 *
 * Every form follows the identical construct order and an identical
 * CEFR distribution per construct (A1, A2, B1, B1, B2, C1), so the five
 * forms are built to be as comparable as reasonably possible without
 * claiming formal psychometric equivalence.
 */

const ENGLISH_PROFILE_TESTS = {

  // =========================================================================
  // TEST A
  // =========================================================================
  A: [
    // --- Grammar ---
    { id:"A-GR-1", construct:"grammar", targetLevel:"A1", difficulty:"easy",
      question:"Sara ___ a teacher.",
      options:["is","are","am","be"], correctAnswer:0,
      explanation:"Third-person singular subjects take 'is'." },
    { id:"A-GR-2", construct:"grammar", targetLevel:"A2", difficulty:"easy",
      question:"Yesterday, we ___ to the cinema.",
      options:["go","goes","went","gone"], correctAnswer:2,
      explanation:"Past simple of 'go' is 'went'." },
    { id:"A-GR-3", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"I ___ this book twice already.",
      options:["read","have read","reads","am reading"], correctAnswer:1,
      explanation:"Present perfect ('have read') links a past action to the present result ('already')." },
    { id:"A-GR-4", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"If it ___ tomorrow, we'll cancel the picnic.",
      options:["rains","rained","will rain","is raining"], correctAnswer:0,
      explanation:"First conditional: present simple in the if-clause, 'will' in the main clause." },
    { id:"A-GR-5", construct:"grammar", targetLevel:"B2", difficulty:"hard",
      question:"The report ___ by the finance team before the meeting.",
      options:["was prepared","prepared","has prepare","preparing"], correctAnswer:0,
      explanation:"Passive past simple: 'was prepared' — the report receives the action." },
    { id:"A-GR-6", construct:"grammar", targetLevel:"C1", difficulty:"hard",
      question:"Not only ___ late, but he also forgot the documents.",
      options:["he arrived","did he arrive","he did arrive","arrived he"], correctAnswer:1,
      explanation:"Negative adverbial fronting ('Not only') triggers subject-auxiliary inversion." },

    // --- Vocabulary ---
    { id:"A-VO-1", construct:"vocabulary", targetLevel:"A1", difficulty:"easy",
      question:"My brother works in a ___. He sells bread and cakes.",
      options:["bakery","library","hospital","garage"], correctAnswer:0,
      explanation:"A bakery is where bread and cakes are made and sold." },
    { id:"A-VO-2", construct:"vocabulary", targetLevel:"A2", difficulty:"easy",
      question:"Before the trip, we need to ___ a decision about the hotel.",
      options:["make","do","take","have"], correctAnswer:0,
      explanation:"'Make a decision' is the standard collocation." },
    { id:"A-VO-3", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"The meeting was ___ until next week because the manager was ill.",
      options:["put off","put on","put up","put in"], correctAnswer:0,
      explanation:"'Put off' means to postpone." },
    { id:"A-VO-4", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"The instructions were so ___ that nobody understood them.",
      options:["confusing","confused","confuse","confusion"], correctAnswer:0,
      explanation:"The adjective describing the instructions (which cause confusion) is 'confusing'." },
    { id:"A-VO-5", construct:"vocabulary", targetLevel:"B2", difficulty:"hard",
      question:"The company's profits have shown a steady ___ over the past three years.",
      options:["decline","declining","declined","decliner"], correctAnswer:0,
      explanation:"A noun is needed after 'a steady'; 'decline' is the correct noun form." },
    { id:"A-VO-6", construct:"vocabulary", targetLevel:"C1", difficulty:"hard",
      question:"After the long negotiation, both sides finally reached a ___ agreement.",
      options:["mutual","reciprocal","collective","joint"], correctAnswer:0,
      explanation:"'Mutual agreement' is the natural, idiomatic collocation for something both sides accept." },

    // --- Comprehension ---
    { id:"A-CO-1", construct:"comprehension", targetLevel:"A1", difficulty:"easy",
      question:"Notice: 'CLOSED FOR LUNCH 1:00–2:00 PM. Sorry for the inconvenience.'\nWhat time can you visit after lunch?",
      options:["1:00","2:00","12:00","3:00"], correctAnswer:1,
      explanation:"The notice states the closure ends at 2:00 PM." },
    { id:"A-CO-2", construct:"comprehension", targetLevel:"A2", difficulty:"easy",
      question:"Message: 'Hi Sara, I'll be 10 minutes late for our meeting. Can you tell the others to start without me? Thanks, Alex'\nWhat does Alex want Sara to do?",
      options:["Cancel the meeting","Start the meeting without him","Wait for him","Reschedule the meeting"], correctAnswer:1,
      explanation:"Alex explicitly asks the others to start without him." },
    { id:"A-CO-3", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Email: 'Dear Customer, Your order #4521 has been delayed due to a warehouse issue. We expect to deliver it by Friday. As an apology, we've added a 10% discount to your next order.'\nWhat has the company done to apologize?",
      options:["Given a refund","Given a 10% discount on the next order","Cancelled the order","Sent a free replacement item"], correctAnswer:1,
      explanation:"The email specifies a 10% discount on the next order, not a refund or replacement." },
    { id:"A-CO-4", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Passage: 'More companies are allowing employees to work from home part of the week. Supporters say it saves commuting time and improves focus, while critics argue it weakens teamwork and makes training new staff harder.'\nWhat is this passage mainly about?",
      options:["The disadvantages of home working","Different views on remote work","How to train new staff","Why commuting is a problem"], correctAnswer:1,
      explanation:"The passage presents both supporting and critical views — it's about differing opinions, not just disadvantages." },
    { id:"A-CO-5", construct:"comprehension", targetLevel:"B2", difficulty:"hard",
      question:"Passage: 'The food arrived quickly and looked appetizing, but after the first bite, my enthusiasm faded fast. The waiter, noticing my expression, quietly slipped away.'\nWhat can we infer about the food?",
      options:["It tasted disappointing","It was too expensive","It arrived cold","It was too spicy"], correctAnswer:0,
      explanation:"'Enthusiasm faded' and the waiter's reaction imply the food didn't taste good, though this isn't stated directly." },
    { id:"A-CO-6", construct:"comprehension", targetLevel:"C1", difficulty:"hard",
      question:"Passage: 'Another \"quick five-minute call\" that somehow lasted ninety minutes — I really should stop trusting his time estimates.'\nWhat is the writer's tone?",
      options:["Genuinely grateful","Mildly sarcastic","Completely neutral","Extremely angry"], correctAnswer:1,
      explanation:"The quotation marks and exaggerated contrast signal mild, wry sarcasm rather than genuine anger or neutrality." },

    // --- Functional Communication ---
    { id:"A-FU-1", construct:"functional", targetLevel:"A1", difficulty:"easy",
      question:"You meet a new colleague for the first time. What do you say?",
      options:["Nice to meet you.","See you later.","I'm sorry.","Excuse me, where is it?"], correctAnswer:0,
      explanation:"'Nice to meet you' is the standard greeting for a first meeting." },
    { id:"A-FU-2", construct:"functional", targetLevel:"A2", difficulty:"easy",
      question:"You want to arrange a time to meet a friend. What do you say?",
      options:["Are you free on Saturday?","You must come on Saturday.","I go to see you Saturday.","Saturday is come."], correctAnswer:0,
      explanation:"A polite, natural way to propose a meeting time is a question form like 'Are you free...?'" },
    { id:"A-FU-3", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"Your manager gives an instruction but you don't understand part of it. What do you say?",
      options:["Could you clarify what you mean by that?","I don't care about that.","That's wrong.","Never mind, forget it."], correctAnswer:0,
      explanation:"Politely asking for clarification is the appropriate communicative move." },
    { id:"A-FU-4", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"A friend says they're stressed about an exam. What's the most appropriate response?",
      options:["Why don't you make a study plan and take short breaks?","You should just relax and stop studying.","That's not my problem.","Exams are easy, don't worry."], correctAnswer:0,
      explanation:"This response is supportive and offers concrete, realistic advice." },
    { id:"A-FU-5", construct:"functional", targetLevel:"B2", difficulty:"hard",
      question:"A colleague suggests an idea you think won't work, in a meeting. What's the most appropriate response?",
      options:["I see the value in that, but I'm a little concerned about the timeline — could we look at an alternative?","That's a bad idea.","I disagree completely.","Whatever, do what you want."], correctAnswer:0,
      explanation:"This response disagrees diplomatically while acknowledging the colleague's idea." },
    { id:"A-FU-6", construct:"functional", targetLevel:"C1", difficulty:"hard",
      question:"You need to decline a project deadline extension request from a junior colleague, tactfully. What's the most appropriate response?",
      options:["I understand the constraints you're facing, but unfortunately the deadline needs to stay as it is — let's see how I can support you to meet it.","No, that's not possible.","You should have planned better.","I'll think about it, maybe."], correctAnswer:0,
      explanation:"This response is firm but supportive and professional, appropriate for a workplace refusal." },

    // --- Naturalness ---
    { id:"A-NA-1", construct:"naturalness", targetLevel:"A1", difficulty:"easy",
      question:"Which sentence is correct and natural in English?",
      options:["I am 25 years old.","I have 25 years.","I am having 25 years.","I do 25 years."], correctAnswer:0,
      explanation:"English uses 'to be' + age, unlike many other languages that use 'to have'." },
    { id:"A-NA-2", construct:"naturalness", targetLevel:"A2", difficulty:"easy",
      question:"Which is the natural way to say this in English?",
      options:["make a decision","take a decision","do a decision","have a decision"], correctAnswer:0,
      explanation:"'Make a decision' is the most widely natural collocation in everyday English." },
    { id:"A-NA-3", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"Someone says 'Thanks a lot for your help.' What is the most natural reply?",
      options:["No problem at all!","I don't want thanks.","You are welcomed.","It was nothing to me."], correctAnswer:0,
      explanation:"'No problem at all!' is a common, natural, friendly response to thanks." },
    { id:"A-NA-4", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"In a formal email to your professor, which is the most appropriate closing?",
      options:["Best regards,","Bye bye!","See ya,","Cheers mate,"], correctAnswer:0,
      explanation:"'Best regards' matches the formal register expected in academic correspondence." },
    { id:"A-NA-5", construct:"naturalness", targetLevel:"B2", difficulty:"hard",
      question:"Which sounds most natural?",
      options:["I'm really looking forward to the trip.","I have a big waiting for the trip.","I wait with joy for the trip.","I am forward-looking to the trip."], correctAnswer:0,
      explanation:"'Look forward to' is the natural idiomatic expression; the other options are literal, unnatural translations." },
    { id:"A-NA-6", construct:"naturalness", targetLevel:"C1", difficulty:"hard",
      question:"Which word best completes this natural sentence: 'The negotiations reached a ___ before the deadline.'",
      options:["breakthrough","break forward","broken point","breaking success"], correctAnswer:0,
      explanation:"'Reach a breakthrough' is an established, natural collocation; the distractors are invented, unnatural phrases." },
  ],

  // =========================================================================
  // TEST B
  // =========================================================================
  B: [
    // --- Grammar ---
    { id:"B-GR-1", construct:"grammar", targetLevel:"A1", difficulty:"easy",
      question:"They ___ from Brazil.",
      options:["is","am","are","be"], correctAnswer:2,
      explanation:"'They' takes the plural form 'are'." },
    { id:"B-GR-2", construct:"grammar", targetLevel:"A2", difficulty:"easy",
      question:"She ___ her homework before dinner yesterday.",
      options:["finish","finished","finishing","finishes"], correctAnswer:1,
      explanation:"Past simple of a regular verb: 'finished'." },
    { id:"B-GR-3", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"We ___ to that museum before, so we don't need a guide today.",
      options:["went","have been","are going","go"], correctAnswer:1,
      explanation:"Present perfect ('have been') expresses past experience relevant to now." },
    { id:"B-GR-4", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"This is the hotel ___ we stayed last summer.",
      options:["which","where","who","whose"], correctAnswer:1,
      explanation:"'Where' introduces a relative clause referring to a place." },
    { id:"B-GR-5", construct:"grammar", targetLevel:"B2", difficulty:"hard",
      question:"She said that she ___ the report the next day.",
      options:["will finish","would finish","finishes","finish"], correctAnswer:1,
      explanation:"Reported speech shifts 'will' back to 'would'." },
    { id:"B-GR-6", construct:"grammar", targetLevel:"C1", difficulty:"hard",
      question:"If she ___ harder at university, she would have a better job now.",
      options:["studied","had studied","studies","would study"], correctAnswer:1,
      explanation:"Mixed conditional: past perfect in the if-clause with a present result." },

    // --- Vocabulary ---
    { id:"B-VO-1", construct:"vocabulary", targetLevel:"A1", difficulty:"easy",
      question:"He was thirsty, so he asked for a glass of ___.",
      options:["water","paper","chair","shoe"], correctAnswer:0,
      explanation:"You drink water when thirsty." },
    { id:"B-VO-2", construct:"vocabulary", targetLevel:"A2", difficulty:"easy",
      question:"Please ___ attention to the safety instructions before takeoff.",
      options:["pay","make","do","take"], correctAnswer:0,
      explanation:"'Pay attention' is the standard collocation." },
    { id:"B-VO-3", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"The flight was ___ due to bad weather.",
      options:["called off","called up","called in","called out"], correctAnswer:0,
      explanation:"'Called off' means cancelled." },
    { id:"B-VO-4", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"The lecture was so ___ that several students fell asleep.",
      options:["dull","dully","dullness","dulled"], correctAnswer:0,
      explanation:"The adjective form 'dull' (boring) fits after 'so'." },
    { id:"B-VO-5", construct:"vocabulary", targetLevel:"B2", difficulty:"hard",
      question:"The university is planning to ___ its research funding next year.",
      options:["expand","expanse","expander","expandable"], correctAnswer:0,
      explanation:"A verb is needed after 'to'; 'expand' fits." },
    { id:"B-VO-6", construct:"vocabulary", targetLevel:"C1", difficulty:"hard",
      question:"Their business partnership was based on ___ trust rather than a written contract.",
      options:["mutual","shared","joint","common"], correctAnswer:0,
      explanation:"'Mutual trust' is the natural collocation for trust that both sides feel toward each other." },

    // --- Comprehension ---
    { id:"B-CO-1", construct:"comprehension", targetLevel:"A1", difficulty:"easy",
      question:"Notice: 'GATE CHANGE: Flight TK205 now departs from Gate 12.'\nWhere does the flight now depart from?",
      options:["Gate 12","Gate 20","Gate 21","Gate 2"], correctAnswer:0,
      explanation:"The notice states the new gate is 12." },
    { id:"B-CO-2", construct:"comprehension", targetLevel:"A2", difficulty:"easy",
      question:"Message: 'Hi Tom, the library closes at 6pm today, not 9pm as usual, because of a staff meeting. See you there before 5:30! Maria'\nWhat does Maria suggest?",
      options:["Meet before 5:30","Meet after 9pm","Cancel the meeting","Go to a different library"], correctAnswer:0,
      explanation:"Maria explicitly says 'see you there before 5:30'." },
    { id:"B-CO-3", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Email: 'Dear Student, your application has been received. Due to high demand, decisions will be sent by email in three weeks instead of the usual two. No action is needed from you at this time.'\nWhen will the student receive a decision?",
      options:["In two weeks","In three weeks","Immediately","Never"], correctAnswer:1,
      explanation:"The email states decisions will now take three weeks instead of the usual two." },
    { id:"B-CO-4", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Passage: 'Many first-year students must choose between dormitories on campus and private apartments nearby. Dorms are cheaper and closer to classes, but apartments offer more privacy and independence.'\nWhat is this mainly about?",
      options:["The cost of apartments","A comparison of housing options","How to apply for a dorm","Why students want privacy"], correctAnswer:1,
      explanation:"The passage compares two housing options across several factors." },
    { id:"B-CO-5", construct:"comprehension", targetLevel:"B2", difficulty:"hard",
      question:"Passage: 'She checked her phone for the third time in five minutes, then finally set it face-down on the table.'\nWhat can we infer about her?",
      options:["She was bored of the phone","She was trying to stop checking it","She lost her phone","She was calling someone"], correctAnswer:1,
      explanation:"Setting the phone face-down after repeated checking implies a deliberate effort to resist checking it further." },
    { id:"B-CO-6", construct:"comprehension", targetLevel:"C1", difficulty:"hard",
      question:"Passage: 'I suppose the \"brief update\" meeting could have been an email, but here we are, an hour later.'\nWhat is the writer implying?",
      options:["The meeting was efficient","The meeting was longer than necessary","The writer enjoyed the meeting","The writer wanted more meetings"], correctAnswer:1,
      explanation:"The contrast between 'brief update' and 'an hour later' implies the meeting was unnecessarily long." },

    // --- Functional Communication ---
    { id:"B-FU-1", construct:"functional", targetLevel:"A1", difficulty:"easy",
      question:"You want to ask someone the way to the station politely. What do you say?",
      options:["Excuse me, could you tell me the way to the station?","Where station?","Go station now.","Station, please, quick."], correctAnswer:0,
      explanation:"A polite request begins with 'Excuse me, could you...?'" },
    { id:"B-FU-2", construct:"functional", targetLevel:"A2", difficulty:"easy",
      question:"You want to invite a classmate to study together. What do you say?",
      options:["Would you like to study together this weekend?","You must study with me.","Study now with me.","I want you study."], correctAnswer:0,
      explanation:"'Would you like to...?' is a polite, natural invitation." },
    { id:"B-FU-3", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"You didn't understand a professor's instructions for an assignment. What's most appropriate?",
      options:["Sorry, could you go over that part again?","That makes no sense at all.","I won't do it then.","Whatever, I'll guess."], correctAnswer:0,
      explanation:"Politely asking the professor to repeat the instructions is the appropriate move." },
    { id:"B-FU-4", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"A friend can't decide between two university courses. What's most appropriate?",
      options:["Maybe list the pros and cons of each before deciding.","Just pick either one, it doesn't matter.","You should ask nobody.","Courses are all the same."], correctAnswer:0,
      explanation:"Suggesting a practical decision-making method is helpful and appropriate." },
    { id:"B-FU-5", construct:"functional", targetLevel:"B2", difficulty:"hard",
      question:"A group member submits work with several errors close to the deadline. What's most appropriate?",
      options:["Thanks for getting this done — could we go through a few points together before we submit?","This is full of mistakes.","You should redo everything.","I'll just fix it myself without telling you."], correctAnswer:0,
      explanation:"This response is constructive and collaborative rather than critical or dismissive." },
    { id:"B-FU-6", construct:"functional", targetLevel:"C1", difficulty:"hard",
      question:"You must tell a supervisor their proposed research method has a significant flaw. What's most appropriate?",
      options:["I think the approach has real strengths, though I'd like to flag a methodological concern before we proceed.","This method is wrong.","I don't think this will work at all.","Someone else should redesign this."], correctAnswer:0,
      explanation:"This response is tactful, balanced, and appropriately hedged for addressing a supervisor." },

    // --- Naturalness ---
    { id:"B-NA-1", construct:"naturalness", targetLevel:"A1", difficulty:"easy",
      question:"Which is correct and natural?",
      options:["I am hungry.","I have hungry.","I am having hunger.","I do hunger."], correctAnswer:0,
      explanation:"English expresses hunger with 'to be' + adjective." },
    { id:"B-NA-2", construct:"naturalness", targetLevel:"A2", difficulty:"easy",
      question:"Which is the natural way to say this?",
      options:["do a mistake","make a mistake","have a mistake","take a mistake"], correctAnswer:1,
      explanation:"'Make a mistake' is the standard natural collocation." },
    { id:"B-NA-3", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"Someone says 'Sorry I'm late.' What is the most natural reply?",
      options:["No worries, we just started.","I don't forgive you.","You are late, this is bad.","It doesn't matter to nobody."], correctAnswer:0,
      explanation:"'No worries, we just started' is a common, relaxed, natural response." },
    { id:"B-NA-4", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"In a formal letter to a university admissions office, which opening is most appropriate?",
      options:["Dear Sir or Madam,","Hey guys,","Yo,","What's up,"], correctAnswer:0,
      explanation:"'Dear Sir or Madam' matches the formal register expected in official correspondence." },
    { id:"B-NA-5", construct:"naturalness", targetLevel:"B2", difficulty:"hard",
      question:"Which sounds most natural?",
      options:["I have to catch up on my emails this weekend.","I have to arrive to my emails this weekend.","I must reach my emails this weekend.","I need to touch my emails this weekend."], correctAnswer:0,
      explanation:"'Catch up on' is the natural idiomatic phrase for dealing with a backlog." },
    { id:"B-NA-6", construct:"naturalness", targetLevel:"C1", difficulty:"hard",
      question:"Which word best completes this natural sentence: 'Her argument didn't quite ___ with the rest of the presentation.'",
      options:["align","aline","alignment","aligning"], correctAnswer:0,
      explanation:"'Align with' is the natural verb collocation; the other options are grammatically wrong forms." },
  ],

  // =========================================================================
  // TEST C
  // =========================================================================
  C: [
    // --- Grammar ---
    { id:"C-GR-1", construct:"grammar", targetLevel:"A1", difficulty:"easy",
      question:"He ___ a doctor.",
      options:["am","is","are","be"], correctAnswer:1,
      explanation:"Third-person singular takes 'is'." },
    { id:"C-GR-2", construct:"grammar", targetLevel:"A2", difficulty:"easy",
      question:"We ___ dinner at 8 last night.",
      options:["have","had","having","haves"], correctAnswer:1,
      explanation:"Past simple of 'have' is 'had'." },
    { id:"C-GR-3", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"I ___ the email before you called.",
      options:["had sent","have sent","sent","was sending"], correctAnswer:0,
      explanation:"Past perfect ('had sent') shows an action completed before another past action ('called')." },
    { id:"C-GR-4", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"This is the client ___ project we discussed yesterday.",
      options:["whose","who","which","whom"], correctAnswer:0,
      explanation:"'Whose' shows possession — the client's project." },
    { id:"C-GR-5", construct:"grammar", targetLevel:"B2", difficulty:"hard",
      question:"If the contract ___ by Friday, we will lose the deal.",
      options:["isn't signed","doesn't sign","isn't signing","won't sign"], correctAnswer:0,
      explanation:"Passive present simple in a first conditional: the contract is signed (by someone)." },
    { id:"C-GR-6", construct:"grammar", targetLevel:"C1", difficulty:"hard",
      question:"Rarely ___ such a competitive market before.",
      options:["have we seen","we have seen","we saw","did we saw"], correctAnswer:0,
      explanation:"Negative adverb fronting ('Rarely') triggers subject-auxiliary inversion." },

    // --- Vocabulary ---
    { id:"C-VO-1", construct:"vocabulary", targetLevel:"A1", difficulty:"easy",
      question:"She works in an ___ with many desks and computers.",
      options:["office","kitchen","garden","river"], correctAnswer:0,
      explanation:"Desks and computers describe an office." },
    { id:"C-VO-2", construct:"vocabulary", targetLevel:"A2", difficulty:"easy",
      question:"He needs to ___ an appointment with the dentist.",
      options:["make","do","take","have"], correctAnswer:0,
      explanation:"'Make an appointment' is the standard collocation." },
    { id:"C-VO-3", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"The launch of the new product was ___ to next month.",
      options:["put back","put down","put in","put over"], correctAnswer:0,
      explanation:"'Put back' means postponed to a later date." },
    { id:"C-VO-4", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"His presentation was extremely ___, and the audience stayed fully engaged.",
      options:["engaging","engage","engagement","engaged"], correctAnswer:0,
      explanation:"'Engaging' (holding interest) fits; 'engaged' would describe the audience, not the presentation." },
    { id:"C-VO-5", construct:"vocabulary", targetLevel:"B2", difficulty:"hard",
      question:"The company aims to ___ its market share in the next quarter.",
      options:["increase","increasement","increaser","increasingly"], correctAnswer:0,
      explanation:"A verb is needed after 'to'; 'increase' fits ('increasement' is not a word)." },
    { id:"C-VO-6", construct:"vocabulary", targetLevel:"C1", difficulty:"hard",
      question:"The two departments finally reached a ___ solution that satisfied both sides.",
      options:["mutually acceptable","reciprocal","joint","collective"], correctAnswer:0,
      explanation:"'Mutually acceptable' precisely captures a solution both sides agree to; the distractors don't fit as naturally." },

    // --- Comprehension ---
    { id:"C-CO-1", construct:"comprehension", targetLevel:"A1", difficulty:"easy",
      question:"Notice: 'MEETING ROOM B — RESERVED 2:00–3:00 PM'\nCan you use Meeting Room B at 2:30 PM?",
      options:["No","Yes","Maybe","Only on Fridays"], correctAnswer:0,
      explanation:"2:30 PM falls within the reserved period." },
    { id:"C-CO-2", construct:"comprehension", targetLevel:"A2", difficulty:"easy",
      question:"Message: 'Hi James, the client call has moved to 4pm instead of 3pm. Please update your calendar. Layla'\nWhat should James do?",
      options:["Cancel the call","Update his calendar","Call the client now","Ignore the message"], correctAnswer:1,
      explanation:"Layla directly asks James to update his calendar." },
    { id:"C-CO-3", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Email: 'Dear Team, due to a system upgrade, the shared drive will be unavailable this Saturday from 9am to 1pm. Please save any urgent files locally before then.'\nWhat should the team do before Saturday 9am?",
      options:["Delete old files","Save urgent files locally","Come into the office","Contact IT"], correctAnswer:1,
      explanation:"The email instructs staff to save urgent files locally before the drive becomes unavailable." },
    { id:"C-CO-4", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Passage: 'Many organizations are redesigning their offices to support hybrid work, with fewer individual desks and more shared spaces for collaboration. The goal is to make in-office days worth the commute.'\nWhat is this mainly about?",
      options:["Companies are removing all offices","Offices are being redesigned for hybrid work","Employees no longer commute","Collaboration is no longer valued"], correctAnswer:1,
      explanation:"The passage describes offices being reshaped to fit hybrid work patterns." },
    { id:"C-CO-5", construct:"comprehension", targetLevel:"B2", difficulty:"hard",
      question:"Passage: 'He glanced at the clock, then back at the unfinished slides, and quietly closed his laptop.'\nWhat can we infer?",
      options:["He finished early","He decided to stop working on the slides for now","He was very confident","He deleted the slides"], correctAnswer:1,
      explanation:"Glancing at the clock and closing the laptop while slides are unfinished implies he stopped for now, likely due to time." },
    { id:"C-CO-6", construct:"comprehension", targetLevel:"C1", difficulty:"hard",
      question:"Passage: 'Of course the client \"just has a few small changes\" — only forty of them, and all due by tomorrow.'\nWhat is the writer's tone?",
      options:["Genuinely pleased","Wry, sarcastic frustration","Completely calm","Very excited"], correctAnswer:1,
      explanation:"The exaggerated contrast between 'a few small changes' and 'forty of them' signals sarcastic frustration." },

    // --- Functional Communication ---
    { id:"C-FU-1", construct:"functional", targetLevel:"A1", difficulty:"easy",
      question:"You arrive at a meeting late. What do you say?",
      options:["Sorry I'm late.","Late I am.","I am the late.","Excuse late."], correctAnswer:0,
      explanation:"'Sorry I'm late' is the natural, standard apology." },
    { id:"C-FU-2", construct:"functional", targetLevel:"A2", difficulty:"easy",
      question:"You want to arrange a call with a colleague. What do you say?",
      options:["Are you available for a call tomorrow?","You must call me tomorrow.","Call happens tomorrow.","Tomorrow call must."], correctAnswer:0,
      explanation:"A polite question is the natural way to propose a call." },
    { id:"C-FU-3", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"A client's instructions in an email are unclear. What's most appropriate?",
      options:["Could you clarify what you mean by point 3?","Your email is confusing.","I don't understand anything you wrote.","Please write better next time."], correctAnswer:0,
      explanation:"Politely and specifically asking for clarification is the professional response." },
    { id:"C-FU-4", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"A colleague is overwhelmed with tasks. What's most appropriate?",
      options:["Maybe we could prioritize the most urgent tasks together?","That's your problem, not mine.","You should work faster.","Just do everything at once."], correctAnswer:0,
      explanation:"This response is supportive and offers to collaborate on a solution." },
    { id:"C-FU-5", construct:"functional", targetLevel:"B2", difficulty:"hard",
      question:"A manager proposes a plan you think is risky. What's most appropriate?",
      options:["I can see why that could work, but I'd like to raise a concern about the risk involved.","That plan will fail.","I don't agree with anything you said.","Do whatever you think, I don't care."], correctAnswer:0,
      explanation:"This response voices a concern diplomatically while acknowledging the manager's reasoning." },
    { id:"C-FU-6", construct:"functional", targetLevel:"C1", difficulty:"hard",
      question:"You need to tell an important client that a deadline will be missed. What's most appropriate?",
      options:["I want to flag early that we're facing a short delay, and here's how we plan to make sure quality isn't affected.","We're not going to make it, sorry.","There's nothing we can do about the delay.","It's not really our fault."], correctAnswer:0,
      explanation:"This response is proactive, professional, and reassuring — appropriate for client communication." },

    // --- Naturalness ---
    { id:"C-NA-1", construct:"naturalness", targetLevel:"A1", difficulty:"easy",
      question:"Which sentence is correct and natural?",
      options:["I am cold.","I have cold.","I do cold.","I am having cold."], correctAnswer:0,
      explanation:"English expresses temperature sensation with 'to be' + adjective." },
    { id:"C-NA-2", construct:"naturalness", targetLevel:"A2", difficulty:"easy",
      question:"Which is the natural collocation?",
      options:["make an effort","do an effort","take an effort","have an effort"], correctAnswer:0,
      explanation:"'Make an effort' is the standard, natural collocation." },
    { id:"C-NA-3", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"Someone says 'Congratulations on the promotion!' What's the most natural reply?",
      options:["Thank you, I really appreciate it!","I don't need congratulations.","It was expected of course.","Congratulations back to you too, wow."], correctAnswer:0,
      explanation:"A simple, gracious thank-you is the natural response to congratulations." },
    { id:"C-NA-4", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"In a formal business email, which closing is most appropriate?",
      options:["Kind regards,","Later,","Peace out,","Talk soon bro,"], correctAnswer:0,
      explanation:"'Kind regards' fits the formal register of business correspondence." },
    { id:"C-NA-5", construct:"naturalness", targetLevel:"B2", difficulty:"hard",
      question:"Which sounds most natural?",
      options:["We need to touch base before the client call.","We need to touch the base before client call.","We need to reach the base with client call.","We need to hit the base for client call."], correctAnswer:0,
      explanation:"'Touch base' is a fixed idiomatic expression meaning to briefly check in with someone." },
    { id:"C-NA-6", construct:"naturalness", targetLevel:"C1", difficulty:"hard",
      question:"Which word best completes: 'The two proposals ___ significantly in terms of cost.'",
      options:["differ","differentiate","different","difference"], correctAnswer:0,
      explanation:"A verb is needed; 'differ' (to be different) is the correct natural choice." },
  ],

  // =========================================================================
  // TEST D
  // =========================================================================
  D: [
    // --- Grammar ---
    { id:"D-GR-1", construct:"grammar", targetLevel:"A1", difficulty:"easy",
      question:"We ___ students.",
      options:["is","am","are","be"], correctAnswer:2,
      explanation:"'We' takes the plural form 'are'." },
    { id:"D-GR-2", construct:"grammar", targetLevel:"A2", difficulty:"easy",
      question:"I ___ my keys yesterday and had to call a locksmith.",
      options:["lose","lost","losing","loses"], correctAnswer:1,
      explanation:"Past simple of 'lose' is 'lost'." },
    { id:"D-GR-3", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"She ___ in this city for five years now.",
      options:["has lived","lived","is living","live"], correctAnswer:0,
      explanation:"Present perfect ('has lived') expresses a state continuing up to now, with 'for five years'." },
    { id:"D-GR-4", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"The professor ___ class I enjoy most is retiring this year.",
      options:["whose","who","which","that"], correctAnswer:0,
      explanation:"'Whose' shows possession: the professor's class." },
    { id:"D-GR-5", construct:"grammar", targetLevel:"B2", difficulty:"hard",
      question:"He told me that the assignment ___ by Monday.",
      options:["had to be submitted","has to submit","must submitted","submits"], correctAnswer:0,
      explanation:"Passive obligation in reported speech: the assignment is submitted (by someone)." },
    { id:"D-GR-6", construct:"grammar", targetLevel:"C1", difficulty:"hard",
      question:"Had I known about the deadline change, I ___ differently.",
      options:["would have planned","would plan","will plan","planned"], correctAnswer:0,
      explanation:"Inverted third conditional: 'Had I known' (= 'If I had known') requires 'would have + past participle'." },

    // --- Vocabulary ---
    { id:"D-VO-1", construct:"vocabulary", targetLevel:"A1", difficulty:"easy",
      question:"I need to buy some ___ to write my notes.",
      options:["paper","window","chair","plate"], correctAnswer:0,
      explanation:"You write notes on paper." },
    { id:"D-VO-2", construct:"vocabulary", targetLevel:"A2", difficulty:"easy",
      question:"Can you ___ care of my plants while I'm away?",
      options:["take","make","do","have"], correctAnswer:0,
      explanation:"'Take care of' is the standard collocation." },
    { id:"D-VO-3", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"I need to ___ my thesis before the deadline.",
      options:["hand in","hand out","hand over","hand up"], correctAnswer:0,
      explanation:"'Hand in' means to submit work." },
    { id:"D-VO-4", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"The lecture was ___ because the professor used so many real examples.",
      options:["memorable","memory","remember","memorize"], correctAnswer:0,
      explanation:"'Memorable' (worth remembering) is the correct adjective form." },
    { id:"D-VO-5", construct:"vocabulary", targetLevel:"B2", difficulty:"hard",
      question:"Her thesis presents a compelling ___ for changing the current policy.",
      options:["argument","arguing","argue","argumentative"], correctAnswer:0,
      explanation:"A noun is needed after 'a compelling'; 'argument' fits." },
    { id:"D-VO-6", construct:"vocabulary", targetLevel:"C1", difficulty:"hard",
      question:"The committee's decision was based on ___ evidence rather than personal opinion.",
      options:["objective","subjective","reasonable","logical"], correctAnswer:0,
      explanation:"'Objective' contrasts precisely with 'personal opinion', which is the point being made." },

    // --- Comprehension ---
    { id:"D-CO-1", construct:"comprehension", targetLevel:"A1", difficulty:"easy",
      question:"Notice: 'LIBRARY QUIET ZONE — NO PHONE CALLS'\nWhat can't you do here?",
      options:["Read books","Make phone calls","Sit down","Use a laptop"], correctAnswer:1,
      explanation:"The notice explicitly forbids phone calls." },
    { id:"D-CO-2", construct:"comprehension", targetLevel:"A2", difficulty:"easy",
      question:"Message: 'Hi Carlos, I left my notebook in the study room. Could you check if it's still there? Nina'\nWhat does Nina ask Carlos to do?",
      options:["Buy a new notebook","Check the study room","Bring his own notes","Cancel their meeting"], correctAnswer:1,
      explanation:"Nina directly asks Carlos to check the study room." },
    { id:"D-CO-3", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Email: 'Dear Students, the deadline for the essay has been extended by one week due to technical issues with the submission portal. No further extensions will be granted.'\nWhy was the deadline extended?",
      options:["Students asked for more time","Technical issues with the portal","The professor was ill","The essay topic changed"], correctAnswer:1,
      explanation:"The email states the extension was due to technical issues with the portal." },
    { id:"D-CO-4", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Passage: 'Some students prefer studying alone because it lets them focus without distraction, while others prefer group study for the chance to discuss ideas and check their understanding.'\nWhat is the main idea?",
      options:["Group study is always better","Different students prefer different study methods","Studying alone is a waste of time","Only group study helps understanding"], correctAnswer:1,
      explanation:"The passage presents two valid preferences without ranking one as universally better." },
    { id:"D-CO-5", construct:"comprehension", targetLevel:"B2", difficulty:"hard",
      question:"Passage: 'He read the feedback twice, closed the document, and didn't open it again for the rest of the day.'\nWhat can we infer?",
      options:["He was pleased with the feedback","The feedback affected him negatively","He forgot about the feedback","He printed the feedback"], correctAnswer:1,
      explanation:"Reading feedback twice and then avoiding it suggests the feedback was hard to process, i.e. negative for him." },
    { id:"D-CO-6", construct:"comprehension", targetLevel:"C1", difficulty:"hard",
      question:"Passage: 'Apparently the \"minor revision\" means rewriting the entire second chapter — good thing I had nothing else planned this week.'\nWhat is the writer's tone?",
      options:["Genuinely relieved","Sarcastic / ironic","Neutral and factual","Very excited"], correctAnswer:1,
      explanation:"The exaggerated 'good thing' contradicts the actual burden described, signaling irony." },

    // --- Functional Communication ---
    { id:"D-FU-1", construct:"functional", targetLevel:"A1", difficulty:"easy",
      question:"You want to ask a classmate their name. What do you say?",
      options:["What's your name?","You, name?","Name, you?","Tell name."], correctAnswer:0,
      explanation:"'What's your name?' is the standard question." },
    { id:"D-FU-2", construct:"functional", targetLevel:"A2", difficulty:"easy",
      question:"You want to suggest meeting at a cafe. What do you say?",
      options:["Shall we meet at the cafe at 5?","You come cafe 5.","Cafe 5 must you.","Meet must at cafe."], correctAnswer:0,
      explanation:"'Shall we...?' is a natural way to suggest a plan." },
    { id:"D-FU-3", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"You didn't understand part of a classmate's explanation. What's most appropriate?",
      options:["Sorry, could you explain that part again?","That makes no sense.","I give up understanding.","Never mind, forget it."], correctAnswer:0,
      explanation:"Politely asking for repetition is the appropriate response." },
    { id:"D-FU-4", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"A friend is nervous about a job interview. What's most appropriate?",
      options:["Maybe practice a few common questions beforehand?","Don't worry, interviews are pointless.","You'll probably fail anyway.","Just say whatever comes to mind."], correctAnswer:0,
      explanation:"This response is supportive and gives practical, encouraging advice." },
    { id:"D-FU-5", construct:"functional", targetLevel:"B2", difficulty:"hard",
      question:"A friend asks to borrow money again after not repaying you last time. What's most appropriate?",
      options:["I'd rather not this time, since the last loan hasn't been paid back yet.","No way, never again.","You always do this, it's annoying.","Fine, but I hate you for asking."], correctAnswer:0,
      explanation:"This response sets a boundary honestly but without hostility." },
    { id:"D-FU-6", construct:"functional", targetLevel:"C1", difficulty:"hard",
      question:"You must tell a co-author their section needs significant revision before submission. What's most appropriate?",
      options:["Your section raises great points — I think it would be even stronger with a bit more evidence before we submit.","This section isn't good enough.","You need to rewrite this.","I'll just rewrite it myself without asking."], correctAnswer:0,
      explanation:"This response is constructive, specific, and collegial, appropriate between co-authors." },

    // --- Naturalness ---
    { id:"D-NA-1", construct:"naturalness", targetLevel:"A1", difficulty:"easy",
      question:"Which sentence is correct and natural?",
      options:["I am tired.","I have tired.","I do tired.","I am having tired."], correctAnswer:0,
      explanation:"English expresses tiredness with 'to be' + adjective." },
    { id:"D-NA-2", construct:"naturalness", targetLevel:"A2", difficulty:"easy",
      question:"Which is natural?",
      options:["make progress","do progress","take progress","have progress"], correctAnswer:0,
      explanation:"'Make progress' is the standard, natural collocation." },
    { id:"D-NA-3", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"Someone says 'I failed my exam.' What's the most natural, supportive reply?",
      options:["I'm sorry to hear that — you can always retake it.","That's your fault.","Exams don't matter anyway.","I don't care about your exam."], correctAnswer:0,
      explanation:"This is empathetic and offers a constructive, natural response." },
    { id:"D-NA-4", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"In a formal email to a professor requesting an extension, which is most appropriate?",
      options:["I am writing to kindly request an extension for the assignment.","Can I get more time or what?","Give me more time please now.","Extension please, thanks bye."], correctAnswer:0,
      explanation:"This matches the formal register expected in academic requests." },
    { id:"D-NA-5", construct:"naturalness", targetLevel:"B2", difficulty:"hard",
      question:"Which sounds most natural?",
      options:["I need to brush up on my grammar before the exam.","I need to brush my grammar up before exam.","I need to clean up my grammar for exam.","I need to sharpen my grammar before exam."], correctAnswer:0,
      explanation:"'Brush up on' is the fixed idiomatic phrase for reviewing a skill." },
    { id:"D-NA-6", construct:"naturalness", targetLevel:"C1", difficulty:"hard",
      question:"Which word best completes: 'Her explanation ___ light on a very confusing topic.'",
      options:["shed","showed","gave","put"], correctAnswer:0,
      explanation:"'Shed light on' is a fixed idiomatic expression meaning to clarify something." },
  ],

  // =========================================================================
  // TEST E
  // =========================================================================
  E: [
    // --- Grammar ---
    { id:"E-GR-1", construct:"grammar", targetLevel:"A1", difficulty:"easy",
      question:"It ___ a sunny day today.",
      options:["is","am","are","be"], correctAnswer:0,
      explanation:"'It' takes 'is' as a third-person singular subject." },
    { id:"E-GR-2", construct:"grammar", targetLevel:"A2", difficulty:"easy",
      question:"They ___ to Japan last spring.",
      options:["travel","traveled","traveling","travels"], correctAnswer:1,
      explanation:"Past simple of 'travel' is 'traveled'." },
    { id:"E-GR-3", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"I ___ my passport, so I can't check in yet.",
      options:["haven't found","didn't find","don't find","not find"], correctAnswer:0,
      explanation:"Present perfect negative ('haven't found') links the past search to the present problem." },
    { id:"E-GR-4", construct:"grammar", targetLevel:"B1", difficulty:"medium",
      question:"This is the hotel ___ we're staying tonight.",
      options:["where","which","who","whose"], correctAnswer:0,
      explanation:"'Where' introduces a relative clause referring to a place." },
    { id:"E-GR-5", construct:"grammar", targetLevel:"B2", difficulty:"hard",
      question:"If the flight ___ , we would have missed the connection.",
      options:["hadn't been delayed","wasn't delayed","isn't delayed","won't be delayed"], correctAnswer:0,
      explanation:"Third conditional passive: 'hadn't been delayed' pairs with 'would have missed'." },
    { id:"E-GR-6", construct:"grammar", targetLevel:"C1", difficulty:"hard",
      question:"So exhausted ___ after the trip that she slept for twelve hours.",
      options:["was she","she was","did she","she did"], correctAnswer:0,
      explanation:"Fronting 'So exhausted' triggers subject-verb inversion: 'was she'." },

    // --- Vocabulary ---
    { id:"E-VO-1", construct:"vocabulary", targetLevel:"A1", difficulty:"easy",
      question:"We need to ___ a taxi to the airport.",
      options:["take","do","make","have"], correctAnswer:0,
      explanation:"'Take a taxi' is the standard collocation." },
    { id:"E-VO-2", construct:"vocabulary", targetLevel:"A2", difficulty:"easy",
      question:"Please ___ sure you have your boarding pass ready.",
      options:["make","do","take","have"], correctAnswer:0,
      explanation:"'Make sure' is the standard collocation." },
    { id:"E-VO-3", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"The trip had to be ___ because of the storm.",
      options:["called off","called up","called in","called out"], correctAnswer:0,
      explanation:"'Called off' means cancelled." },
    { id:"E-VO-4", construct:"vocabulary", targetLevel:"B1", difficulty:"medium",
      question:"The hotel staff were extremely ___, answering every question patiently.",
      options:["helpful","help","helping","helper"], correctAnswer:0,
      explanation:"The adjective 'helpful' describes the staff's behavior." },
    { id:"E-VO-5", construct:"vocabulary", targetLevel:"B2", difficulty:"hard",
      question:"The airline offered a full ___ after the cancellation.",
      options:["refund","refunding","refunder","refundable"], correctAnswer:0,
      explanation:"A noun is needed after 'a full'; 'refund' fits." },
    { id:"E-VO-6", construct:"vocabulary", targetLevel:"C1", difficulty:"hard",
      question:"The two itineraries were ___ similar, differing only in the return date.",
      options:["virtually","actually","literally","totally"], correctAnswer:0,
      explanation:"'Virtually similar' naturally conveys 'almost identical', matching the small difference described." },

    // --- Comprehension ---
    { id:"E-CO-1", construct:"comprehension", targetLevel:"A1", difficulty:"easy",
      question:"Notice: 'BAGGAGE CLAIM — CARROUSEL 4'\nWhere do you collect your bags?",
      options:["Carrousel 4","Gate 4","Check-in 4","Terminal 4"], correctAnswer:0,
      explanation:"The notice specifies Carrousel 4 for baggage claim." },
    { id:"E-CO-2", construct:"comprehension", targetLevel:"A2", difficulty:"easy",
      question:"Message: 'Hi Daniel, our flight is delayed by 2 hours. New boarding time is 6pm. Get some food while we wait! Yuki'\nWhat does Yuki suggest?",
      options:["Go home","Get some food","Change the flight","Complain to staff"], correctAnswer:1,
      explanation:"Yuki explicitly suggests getting some food while waiting." },
    { id:"E-CO-3", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Email: 'Dear Guest, due to renovation work, the hotel pool will be closed from Monday to Wednesday. We apologize for any inconvenience and offer a 15% discount on spa services during this period.'\nWhat is offered as compensation?",
      options:["A free room upgrade","A discount on spa services","A refund","A free breakfast"], correctAnswer:1,
      explanation:"The email specifies a 15% discount on spa services." },
    { id:"E-CO-4", construct:"comprehension", targetLevel:"B1", difficulty:"medium",
      question:"Passage: 'Budget airlines have made international travel more affordable, but passengers often find extra fees for luggage, seat selection, and meals add up quickly.'\nWhat is the main idea?",
      options:["Budget airlines are always cheaper overall","Budget flights can end up costing more than expected","Meals are always free on flights","Luggage is never charged"], correctAnswer:1,
      explanation:"The passage highlights hidden fees that can offset the initial low price." },
    { id:"E-CO-5", construct:"comprehension", targetLevel:"B2", difficulty:"hard",
      question:"Passage: 'She kept refreshing the flight-status page every few minutes, then finally put her phone away and picked up a book instead.'\nWhat can we infer?",
      options:["She stopped worrying about the flight","She gave up trying to check further for now","She missed her flight","She cancelled her ticket"], correctAnswer:1,
      explanation:"Putting the phone away after repeated checking suggests a deliberate pause, not that all worry vanished." },
    { id:"E-CO-6", construct:"comprehension", targetLevel:"C1", difficulty:"hard",
      question:"Passage: 'Naturally, the \"direct flight\" included a two-hour layover — I should really read the fine print next time.'\nWhat is the writer's tone?",
      options:["Sincerely thankful","Wry, self-directed humor","Completely angry","Entirely neutral"], correctAnswer:1,
      explanation:"The self-critical remark following the ironic 'naturally' signals wry humor aimed at oneself." },

    // --- Functional Communication ---
    { id:"E-FU-1", construct:"functional", targetLevel:"A1", difficulty:"easy",
      question:"You want to ask for the bill at a restaurant. What do you say?",
      options:["Could we have the bill, please?","Bill me now.","Give bill.","I want pay quick."], correctAnswer:0,
      explanation:"'Could we have the bill, please?' is the polite, standard request." },
    { id:"E-FU-2", construct:"functional", targetLevel:"A2", difficulty:"easy",
      question:"You want to arrange to meet at the airport. What do you say?",
      options:["Shall we meet at the check-in desk at 9?","You must come check-in 9.","Check-in 9 come you.","Meet must airport."], correctAnswer:0,
      explanation:"'Shall we...?' is a natural way to propose a plan." },
    { id:"E-FU-3", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"A hotel receptionist's instructions about checkout time are unclear. What's most appropriate?",
      options:["Sorry, could you confirm what time checkout is exactly?","Your instructions make no sense.","I don't understand anything.","Whatever, I'll just guess."], correctAnswer:0,
      explanation:"Politely asking for confirmation is the appropriate response." },
    { id:"E-FU-4", construct:"functional", targetLevel:"B1", difficulty:"medium",
      question:"A friend is anxious about a long flight. What's most appropriate?",
      options:["Maybe bring a book or download some shows beforehand?","Flights are always terrible, just accept it.","You shouldn't fly then.","It doesn't matter what you do."], correctAnswer:0,
      explanation:"This response offers supportive, practical advice." },
    { id:"E-FU-5", construct:"functional", targetLevel:"B2", difficulty:"hard",
      question:"A colleague on a business trip suggests changing the itinerary in a way you think risks missing a meeting. What's most appropriate?",
      options:["I like the idea, but I'm a bit worried it might cut it close for the meeting — could we check the timing?","That won't work, forget it.","I don't trust your plan.","Do it your way, I don't care."], correctAnswer:0,
      explanation:"This response raises a concern diplomatically while remaining open to the suggestion." },
    { id:"E-FU-6", construct:"functional", targetLevel:"C1", difficulty:"hard",
      question:"You must tell a client abroad that a delayed shipment will affect their launch date. What's most appropriate?",
      options:["I want to give you advance notice of a shipping delay, along with the steps we're taking to minimize the impact on your launch.","The shipment is late, sorry.","There's nothing we can do.","This delay isn't our responsibility."], correctAnswer:0,
      explanation:"This response is proactive and solution-focused, appropriate for international client relations." },

    // --- Naturalness ---
    { id:"E-NA-1", construct:"naturalness", targetLevel:"A1", difficulty:"easy",
      question:"Which sentence is correct and natural?",
      options:["I am 30 years old.","I have 30 years.","I do 30 years.","I am having 30 years."], correctAnswer:0,
      explanation:"English uses 'to be' + age." },
    { id:"E-NA-2", construct:"naturalness", targetLevel:"A2", difficulty:"easy",
      question:"Which is natural?",
      options:["make a reservation","do a reservation","take a reservation for yourself","have a reservation made"], correctAnswer:0,
      explanation:"'Make a reservation' is the standard, natural collocation." },
    { id:"E-NA-3", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"Someone says 'Have a safe flight!' What's the most natural reply?",
      options:["Thanks, see you soon!","I don't need safety.","Flight is not dangerous for me.","Thanks for worry."], correctAnswer:0,
      explanation:"'Thanks, see you soon!' is a warm, natural response to this common well-wish." },
    { id:"E-NA-4", construct:"naturalness", targetLevel:"B1", difficulty:"medium",
      question:"In a formal email to a hotel manager about a complaint, which opening is most appropriate?",
      options:["I am writing to raise a concern about my recent stay.","Yo, your hotel had problems.","Hey, fix your hotel.","Complaint! Read now."], correctAnswer:0,
      explanation:"This matches the formal, measured register expected for a written complaint." },
    { id:"E-NA-5", construct:"naturalness", targetLevel:"B2", difficulty:"hard",
      question:"Which sounds most natural?",
      options:["We should touch down around 9pm local time.","We should touch the ground around 9pm local time.","We should land down around 9pm local time.","We should arrive down around 9pm local time."], correctAnswer:0,
      explanation:"'Touch down' is the fixed idiomatic term for a plane landing." },
    { id:"E-NA-6", construct:"naturalness", targetLevel:"C1", difficulty:"hard",
      question:"Which word best completes: 'The delay ___ havoc with our connecting flights.'",
      options:["wreaked","made","did","caused made"], correctAnswer:0,
      explanation:"'Wreak havoc' is a fixed idiomatic collocation meaning to cause significant disruption." },
  ],
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ENGLISH_PROFILE_TESTS };
}
